### ISSUE TITLE
Request textDocument/documentSymbol failed & "expected, found" Error

### ISSUE THREAD

**Issue by ZRNOF** [unfinishedprogram/wgsl-analyzer#3]
#### I ran into a weird problem when I typed this:
![mainError](https://github.com/unfinishedprogram/wgsl-analyzer/assets/89278589/fa273970-2a0f-454c-8687-b459d36a256c)

#### Then when I modify something it jumps out with this error:
![requesterror](https://github.com/unfinishedprogram/wgsl-analyzer/assets/89278589/49679604-ec80-4833-b2b1-7d210ceb968b)

#### I solved it using this method, but I don't know why
![mainErrorResolve](https://github.com/unfinishedprogram/wgsl-analyzer/assets/89278589/2b6f4d9d-aab4-46e1-99d5-1d81145ebb23)

#### Thank you!

Best regards,
Zaron Chen

**Comment by unfinishedprogram** [comment]
Closing, as I'm unable to re-create in the latest 0.4.0 release of the extension. This is likely due to a bug in Naga, which has been patched.
