### ISSUE TITLE
Sytax errors are highlighted (reported?) at the wrong text position

### ISSUE THREAD

**Issue by stefan-tb** [unfinishedprogram/wgsl-analyzer#6]
While the errors itself are working as expected, they are reported on the wrong row/column numbers (which in turn highlights the wrong text sections) in VSCode.

![image](https://github.com/user-attachments/assets/cc36df9a-2c56-4d32-a0b8-eae61180aedc)
![image](https://github.com/user-attachments/assets/4581164b-f615-448d-81bb-946775739aae)

Help would be greatly appreciated.

VSCode
Version: 1.93.0 (user setup)
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by unfinishedprogram** [comment]
Thank you for bringing this issue to my attention.

Would you mind including a full WGSL file that produces this issue?
This may be caused by a misalignment of char/byte offsets, and in this case it would be useful to have the context of what comes before the sections in your screenshots.

**Comment by stefan-tb** [comment]
[Line.zip](https://github.com/user-attachments/files/17110622/Line.zip)
Hi, thanks for your quick response! Ive attached it as .zip to prevent CRLF conversions. Seems to be UTF8 w/o BOM.

**Comment by stefan-tb** [comment]
Works like a charm. Thank **very** much!
